export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",

  OWNER_DASHBOARD: "/owner/dashboard",
  OWNER_PROPERTIES: "/owner/properties",
  OWNER_ADD_PROPERTY: "/owner/properties/add",
  OWNER_ROOMS: "/owner/rooms",
  OWNER_EMPLOYEES: "/owner/employees",
  OWNER_BOOKINGS: "/owner/bookings",
  OWNER_AVAILABILITY: "/owner/availability",
  OWNER_INVENTORY: "/owner/inventory",
  OWNER_INVENTORY_SETUP: "/owner/inventory/setup",
  OWNER_INVENTORY_BLOCKS: "/owner/inventory/blocks",
  OWNER_INVENTORY_STOP_SELL: "/owner/inventory/stop-sell",
  OWNER_INVENTORY_HISTORY: "/owner/inventory/history",
  OWNER_PRICING: "/owner/pricing",
  OWNER_REVIEWS: "/owner/reviews",
  OWNER_PAYMENTS: "/owner/payments",
  OWNER_REPORTS: "/owner/reports",
  OWNER_SETTINGS: "/owner/settings",
  OWNER_PROFILE: "/owner/profile",
};
